### ISSUE TITLE
'disk' does not work?

### ISSUE THREAD

**Issue by huglester** [ysfkaya/nova-dynamic-lang#2]
Hello

I have changed 'DISK' (in config file) to media.
but URL still shows 'storage', 

while filesystems.php contains:
```
'media' => [
            'driver' => 'local',
            'root'   => public_path('media'),
        ],
```

Btw, I think FLAG should not be required. And languages should be sortable :)

**Comment by ysfkaya** [comment]
Can you try add url key in your disk? Like that. 

```php
'media' => [
            'driver' => 'local',
            'root'   => public_path('media'),
            'url' => env('APP_URL').'/media'
        ],
```
